import { generatedPunjabiProfiles } from "./punjabi-font-profiles";

export const fontToolsContent: Record<string, { sections: { title: string, content: string }[], disableAutoEnrich?: boolean }> = {
  ...generatedPunjabiProfiles,

  // KRUTI DEV TO UNICODE / MANGAL CONVERTER
  "krutidev-to-unicode": {
    sections: [
      {
        title: "Kruti Dev to Unicode & Mangal Font Converter",
        content: "<p>Convert legacy <strong>Kruti Dev (010, 011, 016, 020, 021) and DevLys</strong> text into universal <strong>Unicode Hindi (Mangal font)</strong> directly in your browser. Whether you are preparing for government typing exams (CPCT, SSC, High Court, UP Police), drafting legal documents, or sharing Hindi text on WhatsApp and websites, this tool provides clean character mapping without broken matras.</p>"
      },
      {
        title: "What is Mangal Font and Why is it Useful?",
        content: "<p><strong>Mangal</strong> is the standard Unicode Devanagari font developed for Indian languages. Unlike legacy fonts like Kruti Dev (which require specific .ttf font files to be installed on each computer), <strong>Unicode text works across all smartphones, computers, tablets, and web browsers</strong>.</p><ul><li><strong>Government Typing Tests (CPCT, High Court, SSC):</strong> Government exams commonly use Mangal font layouts.</li><li><strong>Universal Readability:</strong> Converted Unicode text can be pasted into WhatsApp, email, Google Docs, and web portals.</li><li><strong>In-Browser Processing:</strong> Text conversion runs locally inside your web browser.</li></ul>"
      },
      {
        title: "How to Convert Kruti Dev to Unicode",
        content: "<ol><li><strong>Paste Kruti Dev Text:</strong> Paste your Kruti Dev or DevLys text into the left box.</li><li><strong>Automatic Conversion:</strong> The tool translates your text into clean, readable Unicode on the right.</li><li><strong>Copy or Download:</strong> Click 'Copy' to copy to your clipboard, or download as a Word document.</li></ol>"
      },
      {
        title: "Frequently Asked Questions (FAQ) – Mangal & Kruti Dev",
        content: `
          <p><strong>Q: Is Unicode Hindi the same as Mangal font?</strong><br>A: Yes. Mangal is the default font used by Windows to display standard Devanagari Unicode. Any Unicode text generated by this converter will display in Mangal font on Windows systems.</p>
          <p><strong>Q: Why does my Kruti Dev text show as English letters like 'd', 'j', 'k' on WhatsApp?</strong><br>A: Kruti Dev mapped English keyboard keys to Hindi glyphs. Without the Kruti Dev font installed, devices display raw English letters. Converting to Unicode fixes this so text displays properly on any screen.</p>
          <p><strong>Q: Does this converter handle half-letters (आधे अक्षर) and Reph (र्)?</strong><br>A: Yes, the mapping algorithm handles complex Hindi conjuncts, half-letters (क्, च्, त्, म्, ध्), and reph (र्क, र्म, र्ध).</p>
        `
      }
    ]
  },

  // UNICODE (MANGAL) TO KRUTI DEV CONVERTER
  "unicode-to-krutidev": {
    sections: [
      {
        title: "Unicode (Mangal) to Kruti Dev Converter",
        content: "<p>Convert modern <strong>Unicode Hindi text (Mangal font)</strong> into legacy <strong>Kruti Dev 010 font</strong> format online. Built for DTP operators, print media presses, PageMaker designers, and typists who need Kruti Dev typewriter encoding.</p>"
      },
      {
        title: "Why Convert Mangal / Unicode to Kruti Dev?",
        content: "<ul><li><strong>PageMaker & Photoshop Printing:</strong> Older versions of desktop publishing software require non-Unicode fonts. Converting to Kruti Dev ensures consistent layouts for print presses.</li><li><strong>Traditional Typists:</strong> Offline printing presses and court typists using Kruti Dev key layouts can convert online Unicode articles into their preferred font.</li></ul>"
      },
      {
        title: "Frequently Asked Questions (FAQ)",
        content: `
          <p><strong>Q: How do I use the converted Kruti Dev text in MS Word or PageMaker?</strong><br>A: Copy the output, paste it into your document, and select <strong>'Kruti Dev 010'</strong> as your font family.</p>
        `
      }
    ]
  },

  // CHANAKYA TO UNICODE CONVERTER
  "chanakya-to-unicode": {
    sections: [
      {
        title: "Chanakya to Unicode & Mangal Font Converter",
        content: "<p>Convert legacy <strong>Walkman-Chanakya</strong> font text into universal <strong>Unicode Hindi (Mangal font)</strong> instantly in your browser. This tool is critical for Hindi print journalists, newspaper editors, and publishers who work with traditional PageMaker or Adobe InDesign workflows but need to copy text for web publishing, Word documents, or WhatsApp without it showing up as random English letters.</p>"
      },
      {
        title: "Why Use This Tool?",
        content: "<ul><li><strong>Web and Mobile Readability:</strong> Legacy Chanakya fonts are not supported on smartphones or most websites. Converting to Unicode ensures anyone can read the text anywhere.</li><li><strong>Correct Matra & Ligature Placement:</strong> Unlike simple character replacement, this advanced converter strictly enforces typographic rules, repositioning Chhoti-ee matras (ि), half-characters, and compound conjuncts (like क्ष, त्र, ज्ञ) to their correct Unicode sequence.</li><li><strong>100% Private:</strong> The conversion runs entirely client-side on your device. Your unpublished news articles and drafts are never sent to a server.</li></ul>"
      },
      {
        title: "Chanakya vs Kruti Dev vs Mangal (Unicode)",
        content: `
          <div class="overflow-x-auto my-4">
            <table class="min-w-full divide-y divide-gray-200 dark:divide-gray-700 text-sm">
              <thead class="bg-gray-50 dark:bg-gray-800">
                <tr>
                  <th class="px-4 py-3 text-left font-medium text-gray-700 dark:text-gray-300">Font Name</th>
                  <th class="px-4 py-3 text-left font-medium text-gray-700 dark:text-gray-300">Encoding Type</th>
                  <th class="px-4 py-3 text-left font-medium text-gray-700 dark:text-gray-300">Primary Use Case</th>
                  <th class="px-4 py-3 text-left font-medium text-gray-700 dark:text-gray-300">Web/Mobile Friendly?</th>
                </tr>
              </thead>
              <tbody class="divide-y divide-gray-200 dark:divide-gray-700">
                <tr>
                  <td class="px-4 py-3 font-semibold">Walkman-Chanakya</td>
                  <td class="px-4 py-3">Legacy ASCII (8-bit)</td>
                  <td class="px-4 py-3">Print Media, InDesign, Newspapers</td>
                  <td class="px-4 py-3 text-red-600 font-bold">No</td>
                </tr>
                <tr>
                  <td class="px-4 py-3 font-semibold">Kruti Dev 010</td>
                  <td class="px-4 py-3">Legacy ASCII (8-bit)</td>
                  <td class="px-4 py-3">Govt Exams, Official Typing</td>
                  <td class="px-4 py-3 text-red-600 font-bold">No</td>
                </tr>
                <tr class="bg-gray-50/50 dark:bg-gray-800/50">
                  <td class="px-4 py-3 font-semibold">Mangal (Unicode)</td>
                  <td class="px-4 py-3">Universal Unicode</td>
                  <td class="px-4 py-3">Websites, MS Word, Social Media</td>
                  <td class="px-4 py-3 text-green-600 font-bold">Yes</td>
                </tr>
              </tbody>
            </table>
          </div>
        `
      },
      {
        title: "Frequently Asked Questions (FAQ)",
        content: `
          <p><strong>Q: My Chhoti-ee (ि) matras are showing up on the wrong side of the letter. How do I fix it?</strong><br>A: Legacy fonts like Chanakya often force typists to type the 'f' key (for the matra) before the consonant for visual display. Our converter automatically detects this and shifts the matra to its correct logical position for Unicode.</p>
          <p><strong>Q: Can I use this for Walkman Chanakya 901 or 905?</strong><br>A: Yes. The underlying keyboard mapping for the Walkman Chanakya family is standard across most weights and styles, so the conversion will work perfectly.</p>
        `
      }
    ]
  },

  // UNICODE TO CHANAKYA CONVERTER
  "unicode-to-chanakya": {
    sections: [
      {
        title: "Unicode to Chanakya Font Converter",
        content: "<p>Convert modern <strong>Unicode Hindi text (Mangal font)</strong> into the legacy <strong>Walkman-Chanakya font</strong> format online. This utility is designed specifically for DTP operators, book publishers, and newspaper designers who need to import modern web text back into Adobe PageMaker or InDesign templates that rely on traditional Chanakya typography.</p>"
      },
      {
        title: "How to Use Unicode Hindi in Adobe InDesign using Chanakya",
        content: "<ol><li><strong>Copy Unicode Text:</strong> Copy your modern Hindi text from MS Word, a website, or an email.</li><li><strong>Paste and Convert:</strong> Paste the text into the left panel of this tool. It will instantly convert to Chanakya encoding.</li><li><strong>Copy the Output:</strong> The output will look like random English symbols (e.g., <i>vkt dh rktk [kcj</i>) — this is normal! Copy this output.</li><li><strong>Paste into InDesign:</strong> Paste the symbols into your DTP software. Highlight the text and change the font family to <strong>'Walkman-Chanakya'</strong>. The text will instantly transform into perfect Hindi.</li></ol>"
      },
      {
        title: "Troubleshooting Common Errors",
        content: "<p>If you see broken characters in your design software after conversion, ensure you have the <strong>Walkman-Chanakya</strong> font file (.ttf) installed on your system. Unlike Unicode fonts, legacy fonts are not pre-installed on Windows or macOS. Additionally, ensure you haven't accidentally set your design software's dictionary to auto-correct the 'English' gibberish before applying the font.</p>"
      },
      {
        title: "Frequently Asked Questions (FAQ)",
        content: `
          <p><strong>Q: Why does the output look like English gibberish?</strong><br>A: Chanakya is a legacy font that works by 'hijacking' English characters and replacing their visual appearance with Hindi glyphs. The gibberish is the exact sequence of English keystrokes needed to generate the Hindi words.</p>
          <p><strong>Q: Does this converter reverse the visual order of matras correctly?</strong><br>A: Yes. Our conversion engine specifically reverses the Unicode logical order back into the visual-typing order required by legacy software, including repositioning the Chhoti-ee matra and Reph.</p>
        `
      }
    ]
  },

  "font-detector": {
    sections: [
      {
        title: "Free Font Detector – Identify Legacy Indian & Asian Fonts",
        content: "<p>If you have copied text from an old document or website and it appears as random English letters instead of Hindi, Nepali, or Punjabi script, this tool identifies which legacy font was used (such as Kruti Dev, DevLys, Chanakya, Preeti, Bijoy, InPage, Zawgyi, or AnmolLipi) and lets you convert it to clean Unicode with one click.</p>"
      },
      {
        title: "Why Does Copied Text Sometimes Turn Into Random English Letters?",
        content: "<p>Before Unicode became the global standard, regional typists used legacy fonts that mapped regional characters directly onto English keyboard keys. When that text is pasted onto a phone or modern computer that lacks those specific font files, the device simply displays the underlying English characters. This detector analyzes character patterns to identify the source font so you can convert it to readable Unicode.</p>"
      },
      {
        title: "Features of the Font Detector",
        content: "<ul><li><strong>Automatic Detection:</strong> Identifies common regional fonts like Kruti Dev, Preeti, Bijoy, InPage, Zawgyi, and AnmolLipi.</li><li><strong>1-Click Conversion:</strong> Once detected, you can jump directly to the correct converter.</li><li><strong>In-Browser Processing:</strong> All detection runs locally in your browser.</li></ul>"
      },
      {
        title: "Step-by-Step Guide",
        content: "<ol><li><strong>Paste Text:</strong> Paste your unreadable text into the detection box above.</li><li><strong>Auto-Detection:</strong> The tool identifies the most likely legacy font.</li><li><strong>Convert:</strong> Click 'Convert to Unicode' to translate the text into modern Unicode.</li><li><strong>Copy:</strong> Copy your readable text for use in Word, WhatsApp, or websites.</li></ol>"
      },
      {
        title: "Frequently Asked Questions (FAQ)",
        content: `
          <p><strong>Q: What is the difference between legacy fonts and Unicode?</strong><br>A: Legacy fonts map regional letters onto standard English ASCII keyboard keys and require custom font files. Unicode is supported universally across all modern devices without installing extra fonts.</p>
          <p><strong>Q: Is my pasted text kept private?</strong><br>A: Yes. All font detection and conversion runs locally in your browser.</p>
        `
      }
    ]
  },

  // NEPALI PREETI CONVERTER
  "preeti-to-unicode": {
    sections: [
      {
        title: "Preeti to Unicode Converter – Nepali Font Converter",
        content: "<p>Convert traditional Nepali <strong>Preeti font</strong> text into universal <strong>Nepali Unicode</strong> directly in your browser. Perfect for government notices, news articles, and study materials that need to be read on mobile phones and modern websites.</p>"
      },
      {
        title: "Why Convert Preeti to Unicode?",
        content: "<ul><li><strong>Mobile Compatibility:</strong> Unicode Nepali displays properly on smartphones, tablets, and social media without special font installation.</li><li><strong>Web Publishing:</strong> Unicode text can be searched on Google and shared across WhatsApp, Facebook, and email.</li><li><strong>Local Processing:</strong> Conversion runs locally in your browser.</li></ul>"
      },
      {
        title: "How to Convert Preeti to Unicode",
        content: "<ol><li><strong>Paste Preeti Text:</strong> Paste your legacy Preeti text into the left box.</li><li><strong>Automatic Conversion:</strong> The tool generates clean Nepali Unicode on the right.</li><li><strong>Copy or Download:</strong> Copy your text or save it as a text file.</li></ol>"
      },
      {
        title: "Frequently Asked Questions (FAQ)",
        content: `
          <p><strong>Q: Does this converter support complex Nepali conjunct letters (युक्ताक्षर)?</strong><br>A: Yes. It accurately handles common Nepali conjuncts including त्र, ज्ञ, द्ध, द्व, ष्ट, ष्ठ, and reph (र्).</p>
        `
      }
    ]
  },
  "unicode-to-preeti": {
    sections: [
      {
        title: "Unicode to Preeti Converter – Convert Nepali Unicode to Preeti Font",
        content: "<p>Convert modern standard <strong>Nepali Unicode</strong> into traditional <strong>Preeti font</strong> format for desktop publishers, print presses, and PageMaker templates.</p>"
      },
      {
        title: "Frequently Asked Questions",
        content: `
          <p><strong>Q: Why convert Unicode to Preeti?</strong><br>A: Traditional print houses and newspaper publishing templates often use Preeti font encoding.</p>
        `
      }
    ]
  },

  // BENGALI BIJOY (SUTONNYMJ) CONVERTER
  "bijoy-to-unicode": {
    sections: [
      {
        title: "Bijoy to Unicode Converter – SutonnyMJ to Bangla Unicode",
        content: "<p>Convert legacy <strong>Bijoy (SutonnyMJ)</strong> Bengali font text into standard <strong>Bangla Unicode</strong> online. Helpful for students, journalists, and publishers converting older documents into readable format for web and mobile.</p>"
      },
      {
        title: "Why Use This Converter?",
        content: "<ul><li><strong>Conjunct Support:</strong> Translates Bengali conjunct letters, ref, j-fola, and r-fola.</li><li><strong>Local Browser Processing:</strong> Fast conversion without sending documents across the network.</li><li><strong>Easy Export:</strong> 1-click Copy and download options.</li></ul>"
      },
      {
        title: "Frequently Asked Questions (FAQ)",
        content: `
          <p><strong>Q: What is the difference between SutonnyMJ and Bangla Unicode?</strong><br>A: SutonnyMJ is an older ASCII-based font. Unicode is the international standard supported by all modern operating systems and mobile devices.</p>
        `
      }
    ]
  },
  "unicode-to-bijoy": {
    sections: [
      {
        title: "Unicode to Bijoy Converter – Convert Bangla Unicode to SutonnyMJ",
        content: "<p>Convert modern <strong>Bangla Unicode</strong> text into legacy <strong>Bijoy (SutonnyMJ)</strong> format for use in desktop publishing and graphic design software.</p>"
      },
      {
        title: "Frequently Asked Questions",
        content: `
          <p><strong>Q: Why does Unicode text break in older design tools?</strong><br>A: Older versions of graphics software require ASCII fonts like SutonnyMJ. Converting your Unicode Bangla to Bijoy resolves broken characters in those applications.</p>
        `
      }
    ]
  },
  "sutonnymj-to-unicode": {
    sections: [
      {
        title: "SutonnyMJ to Unicode Converter – Convert SutonnyMJ Bengali Font Online",
        content: "<p>Convert text written in <strong>SutonnyMJ font</strong> to standard <strong>Bangla Unicode</strong> format in your browser.</p>"
      }
    ]
  },
  "unicode-to-sutonnymj": {
    sections: [
      {
        title: "Unicode to SutonnyMJ Converter – Convert Bangla Unicode to SutonnyMJ",
        content: "<p>Convert standard <strong>Bangla Unicode</strong> text to legacy <strong>SutonnyMJ</strong> font format for desktop publishing and printing.</p>"
      }
    ]
  },

  // URDU INPAGE CONVERTER
  "inpage-to-unicode": {
    sections: [
      {
        title: "InPage to Unicode Converter – Urdu Font Converter",
        content: "<p>Convert traditional <strong>InPage Urdu text</strong> into standard <strong>Urdu Unicode</strong> text. Great for bloggers, writers, and students who need to share InPage content on websites, social media, and mobile apps.</p>"
      },
      {
        title: "Features",
        content: "<ul><li><strong>Nastaliq Character Mapping:</strong> Supports Urdu characters (ٹ, ڈ, ڑ, ں, ے, ھ, چ, پ, ژ, گ, ء, ئ, ؤ).</li><li><strong>Private &amp; In-Browser:</strong> Text is processed locally on your device.</li></ul>"
      },
      {
        title: "Frequently Asked Questions (FAQ)",
        content: `
          <p><strong>Q: Why can't I directly copy InPage text to mobile apps?</strong><br>A: InPage uses custom encoding that only displays inside InPage software. Converting to standard Unicode lets the text be read on any modern phone or computer.</p>
        `
      }
    ]
  },
  "unicode-to-inpage": {
    sections: [
      {
        title: "Unicode to InPage Converter – Urdu Unicode to InPage",
        content: "<p>Convert modern <strong>Urdu Unicode</strong> text into <strong>InPage</strong> compatible format to format in InPage desktop software for newspaper and book layout.</p>"
      },
      {
        title: "Frequently Asked Questions",
        content: `
          <p><strong>Q: How do I import Unicode Urdu into InPage?</strong><br>A: Paste your Unicode text here, copy the converted output, and paste it into your InPage text boxes.</p>
        `
      }
    ]
  },

  // BURMESE ZAWGYI CONVERTER
  "zawgyi-to-unicode": {
    sections: [
      {
        title: "Zawgyi to Unicode Converter",
        content: "<p>Instantly convert legacy <strong>Myanmar Zawgyi font</strong> text to the international standard <strong>Myanmar Unicode</strong> format. Since Zawgyi uses a non-standard character encoding, copying and pasting Zawgyi text onto modern smartphones or operating systems often results in unreadable characters or broken text rendering. This tool translates the underlying characters so they display perfectly on any Unicode-compliant device.</p>"
      },
      {
        title: "Why Convert Zawgyi to Unicode?",
        content: "<ul><li><strong>Modern Device Support:</strong> Zawgyi is largely unsupported on modern Android, iOS, and Windows devices without custom font installations. Unicode is supported natively.</li><li><strong>Fix Broken Text:</strong> If you receive a message or download an old document where the Burmese text looks scrambled, converting it to Unicode restores readability.</li><li><strong>Search & Indexing:</strong> Search engines and modern databases require Unicode. Text stored in Zawgyi cannot be accurately searched online.</li></ul>"
      },
      {
        title: "How to Use This Converter",
        content: "<ol><li><strong>Paste your text:</strong> Paste the unreadable Zawgyi text into the input box.</li><li><strong>Auto-conversion:</strong> The tool instantly converts the text into standard Myanmar Unicode using your browser.</li><li><strong>Copy and Use:</strong> Copy the corrected text. You can now safely share it on WhatsApp, Facebook, or use it in Microsoft Word.</li></ol>"
      },
      {
        title: "Privacy & Processing",
        content: "<p>Your text privacy is fully protected. All Zawgyi to Unicode conversion happens locally in your web browser. No data is sent to our servers or stored in the cloud.</p>"
      }
    ]
  },
  "unicode-to-zawgyi": {
    sections: [
      {
        title: "Unicode to Zawgyi Converter",
        content: "<p>Instantly convert standard <strong>Myanmar Unicode</strong> text into the legacy <strong>Zawgyi font</strong> format. While Unicode is the modern global standard, many older smartphones, specialized applications, and legacy databases in Myanmar still rely on the Zawgyi encoding. This tool allows you to translate modern text backward so it renders correctly on older systems.</p>"
      },
      {
        title: "When Do You Need Zawgyi Conversion?",
        content: "<ul><li><strong>Legacy Hardware:</strong> Viewing text on older mobile phones or computers that were configured before Myanmar Unicode became the default standard.</li><li><strong>Old Documents:</strong> Inserting modern text into an older Word document, PDF, or design file (like older versions of Adobe PageMaker or Photoshop) that specifically requires the Zawgyi font.</li><li><strong>Specialized Databases:</strong> Updating legacy databases or websites that have not yet migrated to Unicode.</li></ul>"
      },
      {
        title: "How to Use This Converter",
        content: "<ol><li><strong>Paste your text:</strong> Paste the modern Myanmar Unicode text into the input box.</li><li><strong>Auto-conversion:</strong> The tool instantly converts the text into the Zawgyi encoding structure.</li><li><strong>Copy and Use:</strong> Copy the text and paste it into your legacy application. <em>Note: The text may look broken on your current screen unless you have the Zawgyi font installed, but it will work perfectly on the target legacy device.</em></li></ol>"
      },
      {
        title: "Privacy & Processing",
        content: "<p>Your text privacy is fully protected. All Unicode to Zawgyi conversion happens locally in your web browser. No data is sent to our servers or stored in the cloud.</p>"
      }
    ]
  },

  // WEB FONT CONVERTER
  "web-font-converter": {
    sections: [
      {
        title: "Web Font Converter (TTF, OTF, WOFF, WOFF2)",
        content: "<p>Instantly convert your desktop fonts into web-ready formats. Whether you need to compress a bulky TTF into a fast-loading WOFF2, or extract a TTF from a WOFF file, this tool handles it entirely within your browser.</p>"
      },
      {
        title: "100% Client-Side Privacy",
        content: "<p>Licensed fonts can be expensive. Uploading them to a remote conversion server risks piracy and violates many commercial font licenses. Our converter uses advanced WebAssembly to process the fonts directly on your computer's memory. <strong>Your font files never leave your device.</strong></p>"
      },
      {
        title: "Why use WOFF2?",
        content: "<p>WOFF2 (Web Open Font Format 2) is the modern standard for web typography. It offers a ~30% better compression rate than the original WOFF format, significantly speeding up your website's load time and improving your Core Web Vitals.</p>"
      },
      {
        title: "Frequently Asked Questions",
        content: `
          <div itemscope itemtype="https://schema.org/FAQPage">
            <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
              <h3 itemprop="name">What is the difference between TTF and WOFF2?</h3>
              <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
                <p itemprop="text">TTF (TrueType Font) is a standard desktop font format meant for operating systems and design software. WOFF2 is a highly compressed font format specifically designed for fast loading on websites. You should always convert TTF to WOFF2 before using it in CSS.</p>
              </div>
            </div>
            <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question" class="mt-4">
              <h3 itemprop="name">Can I install WOFF2 files on my Windows or Mac computer?</h3>
              <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
                <p itemprop="text">No. Operating systems do not natively support WOFF2 for system-wide installation. If you have a WOFF2 file that you want to use in Microsoft Word, Photoshop, or Figma, you must convert the WOFF2 file back to TTF or OTF first.</p>
              </div>
            </div>
          </div>
        `
      }
    ]
  },
  "ttf-to-woff2": {
    sections: [
      {
        title: "Convert TTF to WOFF2",
        content: "<p>Convert your TrueType Fonts (TTF) into the highly compressed WOFF2 format for the web. This tool runs 100% locally in your browser, keeping your premium fonts secure from unauthorized uploads.</p>"
      },
      {
        title: "Why convert TTF to WOFF2?",
        content: "<p>While TTF works on the web, it is not compressed. Converting a TTF file to WOFF2 can reduce its file size by up to 50%, resulting in faster page loads and better SEO rankings.</p>"
      },
      {
        title: "Frequently Asked Questions",
        content: `
          <div itemscope itemtype="https://schema.org/FAQPage">
            <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
              <h3 itemprop="name">Is it better to self-host WOFF2 fonts or use Google Fonts?</h3>
              <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
                <p itemprop="text">Self-hosting your own converted WOFF2 fonts is often faster and much more privacy-friendly than using Google Fonts, as it eliminates extra DNS lookups and prevents third-party tracking scripts from running on your site.</p>
              </div>
            </div>
          </div>
        `
      }
    ]
  },
  "otf-to-woff2": {
    sections: [
      {
        title: "Convert OTF to WOFF2",
        content: "<p>Quickly compress your OpenType Fonts (OTF) into WOFF2 web fonts. Our tool runs locally on your device, ensuring complete privacy for your licensed typography.</p>"
      }
    ]
  },
  "woff2-to-ttf": {
    sections: [
      {
        title: "Extract WOFF2 to TTF",
        content: "<p>Need to use a web font in your desktop design software like Photoshop or Illustrator? This tool perfectly decompresses WOFF2 files back into standard TTF format, entirely within your browser.</p>"
      },
      {
        title: "Frequently Asked Questions",
        content: `
          <div itemscope itemtype="https://schema.org/FAQPage">
            <div itemscope itemprop="mainEntity" itemtype="https://schema.org/Question">
              <h3 itemprop="name">Does converting WOFF2 to TTF lose quality?</h3>
              <div itemscope itemprop="acceptedAnswer" itemtype="https://schema.org/Answer">
                <p itemprop="text">No. WOFF2 is simply a compressed container for the original TTF or OTF font data. Converting it back to TTF restores the exact original font file perfectly with zero quality loss.</p>
              </div>
            </div>
          </div>
        `
      }
    ]
  }
};
