import { StyleSettings } from './style-types';

export const FONT_OPTIONS = [
  { label: 'Poppins (Clean Pop)', value: '"Poppins", "Noto Sans Devanagari", "Noto Sans Gurmukhi", sans-serif', files: ['poppins-latin-800-normal.woff2', 'poppins-devanagari-800-normal.woff2', 'NotoSansGurmukhi-Bold.woff2'] },
  { label: 'Baloo 2 (Playful)', value: '"Baloo 2", "Noto Sans Devanagari", "Noto Sans Gurmukhi", sans-serif', files: ['baloo-2-latin-800-normal.woff2', 'baloo-2-devanagari-800-normal.woff2', 'NotoSansGurmukhi-Bold.woff2'] },
  { label: 'Mukta (Modern)', value: '"Mukta", "Noto Sans Devanagari", "Noto Sans Gurmukhi", sans-serif', files: ['mukta-latin-800-normal.woff2', 'mukta-devanagari-800-normal.woff2', 'NotoSansGurmukhi-Bold.woff2'] },
  { label: 'Noto Sans (Clean)', value: '"Noto Sans Devanagari", "Noto Sans Gurmukhi", sans-serif', files: ['NotoSansDevanagari-Bold.woff2', 'NotoSansGurmukhi-Bold.woff2'] },
  { label: 'Hind (Sleek)', value: '"Hind", "Noto Sans Devanagari", "Noto Sans Gurmukhi", sans-serif', files: ['Hind-Bold.woff2', 'NotoSansDevanagari-Bold.woff2', 'NotoSansGurmukhi-Bold.woff2'] },
];

export const PRESETS: Record<string, StyleSettings> = {
  'Clean Pop': {
    fontFamily: '"Poppins", "Noto Sans Devanagari", "Noto Sans Gurmukhi", sans-serif',
    fontSize: 0.065,
    textColor: '#FFFFFF',
    outlineColor: '#000000',
    outlineWidth: 0.015,
    shadowColor: 'rgba(0,0,0,0.5)',
    shadowBlur: 0.01,
    shadowOffsetX: 0.005,
    shadowOffsetY: 0.005,
    backgroundColor: '#000000',
    backgroundOpacity: 0,
    backgroundPadding: 0,
    backgroundRadius: 0,
    textAlign: 'center',
    lineHeight: 1.2
  },
  'Glass': {
    fontFamily: '"Mukta", "Noto Sans Devanagari", "Noto Sans Gurmukhi", sans-serif',
    fontSize: 0.065,
    textColor: '#FFFFFF',
    outlineColor: '#000000',
    outlineWidth: 0,
    shadowColor: 'rgba(0,0,0,0.5)',
    shadowBlur: 0.02,
    shadowOffsetX: 0,
    shadowOffsetY: 0.005,
    backgroundColor: '#000000',
    backgroundOpacity: 0.4,
    backgroundPadding: 0.03,
    backgroundRadius: 0.04,
    textAlign: 'center',
    lineHeight: 1.3
  },
  'Neon': {
    fontFamily: '"Baloo 2", "Noto Sans Devanagari", "Noto Sans Gurmukhi", sans-serif',
    fontSize: 0.07,
    textColor: '#39FF14', // Neon green
    outlineColor: '#000000',
    outlineWidth: 0.005,
    shadowColor: '#39FF14',
    shadowBlur: 0.04,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    backgroundColor: '#000000',
    backgroundOpacity: 0,
    backgroundPadding: 0,
    backgroundRadius: 0,
    textAlign: 'center',
    lineHeight: 1.2
  },
  'Lower Third': {
    fontFamily: '"Poppins", "Noto Sans Devanagari", "Noto Sans Gurmukhi", sans-serif',
    fontSize: 0.04,
    textColor: '#FFFFFF',
    outlineColor: '#000000',
    outlineWidth: 0.005,
    shadowColor: 'rgba(0,0,0,0.8)',
    shadowBlur: 0.01,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    backgroundColor: '#000000',
    backgroundOpacity: 0.8,
    backgroundPadding: 0.015,
    backgroundRadius: 0.01,
    textAlign: 'left',
    lineHeight: 1.3
  },
  'Classic': {
    fontFamily: '"Noto Sans Devanagari", "Noto Sans Gurmukhi", sans-serif',
    fontSize: 0.065,
    textColor: '#FFFFFF',
    outlineColor: '#000000',
    outlineWidth: 0.008,
    shadowColor: 'rgba(0,0,0,0.8)',
    shadowBlur: 0.01,
    shadowOffsetX: 0.005,
    shadowOffsetY: 0.005,
    backgroundColor: '#000000',
    backgroundOpacity: 0,
    backgroundPadding: 0.02,
    backgroundRadius: 0.015,
    textAlign: 'center',
    lineHeight: 1.3
  },
  'Bold Reels': {
    fontFamily: '"Poppins", "Noto Sans Devanagari", "Noto Sans Gurmukhi", sans-serif',
    fontSize: 0.07,
    textColor: '#FFFFFF',
    outlineColor: '#000000',
    outlineWidth: 0.012,
    shadowColor: 'rgba(0,0,0,0.0)',
    shadowBlur: 0,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    backgroundColor: '#000000',
    backgroundOpacity: 0,
    backgroundPadding: 0.02,
    backgroundRadius: 0.015,
    textAlign: 'center',
    lineHeight: 1.2
  },
  'Box': {
    fontFamily: '"Mukta", "Noto Sans Devanagari", "Noto Sans Gurmukhi", sans-serif',
    fontSize: 0.05,
    textColor: '#000000',
    outlineColor: '#000000',
    outlineWidth: 0,
    shadowColor: 'rgba(0,0,0,0)',
    shadowBlur: 0,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    backgroundColor: '#FFDE59',
    backgroundOpacity: 1.0,
    backgroundPadding: 0.025,
    backgroundRadius: 0.02,
    textAlign: 'center',
    lineHeight: 1.3
  },
  'Highlight': {
    fontFamily: '"Baloo 2", "Noto Sans Devanagari", "Noto Sans Gurmukhi", sans-serif',
    fontSize: 0.065,
    textColor: '#FFFFFF',
    outlineColor: '#000000',
    outlineWidth: 0,
    shadowColor: 'rgba(0,0,0,0.5)',
    shadowBlur: 0.02,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    backgroundColor: '#FF3131',
    backgroundOpacity: 0.9,
    backgroundPadding: 0.02,
    backgroundRadius: 0.03,
    textAlign: 'center',
    lineHeight: 1.4
  },
  'Minimal': {
    fontFamily: '"Hind", "Noto Sans Devanagari", "Noto Sans Gurmukhi", sans-serif',
    fontSize: 0.045,
    textColor: '#FFFFFF',
    outlineColor: '#000000',
    outlineWidth: 0.004,
    shadowColor: 'rgba(0,0,0,0.3)',
    shadowBlur: 0.01,
    shadowOffsetX: 0,
    shadowOffsetY: 0,
    backgroundColor: '#000000',
    backgroundOpacity: 0.2,
    backgroundPadding: 0.015,
    backgroundRadius: 0.01,
    textAlign: 'center',
    lineHeight: 1.3
  }
};
