import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer | ConverterForAll",
  description: "Legal disclaimer and limitations of liability for using ConverterForAll.",
};

export default function DisclaimerPage() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-4xl">
      <h1 className="text-4xl font-extrabold tracking-tight lg:text-5xl mb-8">Disclaimer</h1>
      
      <div className="prose prose-slate dark:prose-invert max-w-none prose-lg">
        <p><strong>Last Updated: August 1, 2026</strong></p>
        
        <h2>1. General Information</h2>
        <p>
          The information, digital tools, calculators, file converters, and educational content provided by ConverterForAll (the "Website") are for general informational and utility purposes only. All information on the Site is provided in good faith; however, we make no representation or warranty of any kind, express or implied, regarding the accuracy, adequacy, validity, reliability, availability, or completeness of any information or output generated by our tools.
        </p>
        <p>
          ConverterForAll is owned and operated by Kuldeep Bahl, a Professional Software Engineer. While the platform was developed utilizing industry-standard software engineering practices and drawing on over 14 years of corporate technology experience, it is still provided as a free utility without enterprise-level guarantees.
        </p>

        <h2>2. Use of Conversion Tools at Your Own Risk</h2>
        <p>
          The core functionality of ConverterForAll involves processing digital files—such as converting documents (e.g., Word to PDF), manipulating images (e.g., removing backgrounds), and reformatting data. While we utilize advanced algorithms and, where applicable, secure client-side WebAssembly processing, no software is entirely free of bugs or edge cases.
        </p>
        <p>
          <strong>File Integrity:</strong> You acknowledge that file conversions can occasionally result in formatting loss, unexpected pixelation, missing fonts, or structural corruption. You are strictly advised to retain backup copies of all original files before processing them through ConverterForAll. We accept no responsibility or liability for any lost data, corrupted files, or the financial consequences resulting from a failed or inaccurate conversion.
        </p>

        <h2>3. No Professional Advice</h2>
        <p>
          ConverterForAll provides various calculators, measurement tools, and educational technology articles. This content is provided solely for educational and convenience purposes.
        </p>
        <ul>
          <li><strong>No Financial Advice:</strong> Any tax, financial, or currency calculators provided on the Website are estimates based on standardized mathematical formulas. They do not constitute financial advice. You should always consult with a certified public accountant or financial advisor before making monetary decisions.</li>
          <li><strong>No Legal Advice:</strong> Any document processing tools used for legal contracts (such as converting a legal agreement to PDF) do not establish a secure chain of custody or digital signature validity. We do not provide legal advice, and our tools should not be relied upon for ensuring the legal enforceability of a document.</li>
          <li><strong>No Medical or Engineering Advice:</strong> Any unit converters or scientific calculators provided are for general estimation. They must not be used for critical engineering tolerances, medical dosages, or any scenario where a miscalculation could result in injury, death, or structural failure.</li>
        </ul>

        <h2>4. Educational Content and Tutorials</h2>
        <p>
          The educational blog posts, technology guides, and tutorials published on ConverterForAll are based on the knowledge, research, and professional experience of the author at the time of writing. The technology landscape evolves rapidly. While we strive to periodically update our articles—as detailed in our Editorial Policy—we cannot guarantee that every tutorial reflects the absolute latest version of a software package, web standard, or API.
        </p>
        <p>
          Following the technical advice, coding examples, or software recommendations on this Website is done entirely at your own risk. We are not liable for any system crashes, data loss, or security vulnerabilities that you may experience while attempting to follow our tutorials on your own hardware or servers.
        </p>

        <h2>5. External Links Disclaimer</h2>
        <p>
          The Website may contain links to external websites that are not provided or maintained by or in any way affiliated with ConverterForAll. Please note that we do not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites.
        </p>
        <p>
          When we link to an external resource (such as a software download page, a reference documentation site, or a third-party service), we do so because we believe it provides value to our users. However, a link does not imply an endorsement of that website or its operators. If you choose to click on a third-party link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy and Terms of Service of every site you visit.
        </p>

        <h2>6. Advertising and Affiliate Links</h2>
        <p>
          ConverterForAll is a free service, and its development and hosting costs (such as our Vercel infrastructure) are supported through advertising revenue. 
        </p>
        <p>
          <strong>Google AdSense:</strong> We display automated advertisements provided by the Google AdSense network. We do not manually select these ads, and their presence on our Website does not constitute an endorsement by ConverterForAll or Kuldeep Bahl of the products or services being advertised. Your interactions with advertisers found on or through the Website are solely between you and the advertiser.
        </p>

        <h2>7. Limitation of Liability for Website Availability</h2>
        <p>
          We strive to keep ConverterForAll accessible 24 hours a day, 7 days a week. However, we do not guarantee continuous, uninterrupted, or secure access to the Website. The Website may be temporarily unavailable due to routine maintenance, upgrades, server outages, or circumstances beyond our control (such as regional internet disruptions). We shall not be held liable for any damages, lost productivity, or missed deadlines resulting from your inability to access our file converters or calculators at any given time.
        </p>

        <h2>8. Contact Us</h2>
        <p>
          If you require any more information or have any questions about our site's disclaimer, please feel free to contact us by email.
        </p>
        <p>
          <strong>Email:</strong> [UPDATE BEFORE PUBLISHING]
        </p>
      </div>
    </div>
  );
}
